/*
 * This Java source file was generated by the Gradle 'init' task.jfa[p0j[da9gj[a9d
 */
package Yankees;

public class Library {
	
	public static void main(String arg[]) {
		int x=6;
		System.out.println("new HIHIHIHIHIHHII");
		System.out.println("new2 HIHIHIHIHIHHII");
		
	}
    public boolean someLibraryMethod() {
        return true;
    }
    
    
}
