/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Yankees;

public class Library {
	
	public static void main(String arg[]) {
		System.out.println("new HIHIHIHIHIHHII");
	}
    public boolean someLibraryMethod() {
        return true;
    }
    
    
}
